@API_URL=http://127.0.0.1:8000
@TOKEN=Bearer 12|epodAOvZX8BCa1yBYymsdqoMNtvZz6BeU1gH39p2

### [ person to person follow ]
@person_id=1
POST {{API_URL}}/api/follow/person/{{person_id}} HTTP/1.1
Content-Type: application/json
accept: application/json
Authorization: {{TOKEN}}

### [ person to page follow ]
@page_id=3
POST {{API_URL}}/api/follow/page/{{page_id}} HTTP/1.1
Content-Type: application/json
accept: application/json
Authorization: {{TOKEN}}

